[theme]
primaryColor = "#087F8C"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EBF0F5"
textColor = "#172B4D"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
